_BASE_: "Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: False
    IMAGE_LABEL_LOSS: 'max_size'
  WEIGHTS: "models/BoxSup-C2_Lbase_CLIP_R5021k_640b64_4x.pth"
SOLVER:
  MAX_ITER: 2000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  WARMUP_ITERS: 200
  WARMUP_FACTOR: 0.001
DATASETS:
#  TRAIN: ("lvis_v1_train_norare",)
  TRAIN: ("mts_train",)
DATALOADER:
  SAMPLER_TRAIN: "'TrainingSampler'"
  DATASET_RATIO: [1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4]
  DATASET_INPUT_SIZE: [64]
  USE_RFS: [True]
  DATASET_INPUT_SCALE: [[0.1, 2.0]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: False
  DATASET_ANN: ['box']
  NUM_WORKERS: 1
WITH_IMAGE_LABELS: False
